apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hello-world-go
  janus-idp.io/tekton: hello-world-go
  backstage.io/kubernetes-id: hello-world-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hello-world-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
